---
name: Authen-SASL-SASLprep
version: 1.01
author:
  - 'Claus Färber <CFAERBER@cpan.org>'
abstract: A Stringprep Profile for User Names and Passwords (RFC 4013)
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
  Test::NoWarnings: 0
requires:
  Unicode::Stringprep: 1
configure_requires:
  Module::Build: 0.35
provides:
  Authen::SASL::SASLprep:
    file: lib/Authen/SASL/SASLprep.pm
    version: 1.01
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
