--- #YAML:1.0
name:               Authen-SASL-SASLprep
version:            1.00
abstract:           SASLprep profile (RFC 4013)
author:
    - Claus Faerber <CFAERBER@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:        0
    Test::NoWarnings:  0
requires:
    perl:                 5.006
    Unicode::Stringprep:  1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    perl:  5.008003
